version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config:/etc/loki
      - loki_data:/loki

  promtail:
    image: grafana/promtail:2.5.0
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail/config:/etc/promtail
      - logs:/var/log

volumes:
  grafana-storage:
    external: true
  loki_data:
  logs:
    external: true