name: grafana

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    depends_on:
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config:/etc/loki
      - loki_data:/loki

  promtail:
    image: grafana/promtail
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail/config:/etc/promtail
      - logs:/var/log

volumes:
  grafana-storage:
    external: true
  loki_data:
  logs:
    external: true