{
 "title": "Presentation",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Streaming data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Robot position",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "topic": "m/iotacademy/conestoga/smart/presorter/2/robot/HMI_GVL.M.Rob1.ROBOTPOS.X"
    },
    {
     "topic": "m/iotacademy/conestoga/smart/presorter/2/robot/HMI_GVL.M.Rob1.ROBOTPOS.Y"
    },
    {
     "topic": "m/iotacademy/conestoga/smart/presorter/2/robot/HMI_GVL.M.Rob1.ROBOTPOS.Z"
    }
   ]
  },
  {
   "title": "Motor torque",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "topic": "m/iotacademy/conestoga/smart/presorter/2/robot/HMI_GVL.M.Rob1.MACTTORQUE"
    }
   ]
  },
  { "title": "Historical data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", initialized, running, paused, merror, wsviolation FROM status ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", speedpercentage FROM status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Finished Parts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", finishedpartnum FROM status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cohort 2 / Group 1 / Team 2",
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "options": {
    "content": "* Adam D`Agostino\n* Henrik Liden\n* Philipp Buchinger\n* Shelton Liu"
   }
  },
  {
   "title": "torque",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", motor1, motor2, motor3, motor4 FROM torque ORDER BY \"timestamp\" DESC LIMIT 100 "
    }
   ]
  },
  {
   "title": "position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", x, y, z FROM \"position\" ORDER BY \"timestamp\" DESC "
    }
   ]
  }
 ]
}