server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: custom-json-logs
      static_configs:
          - targets:
                - localhost
            labels:
                job: custom-json-logs
                __path__: /var/log/*.json
      pipeline_stages:
          - json:
                expressions:
                    level: level
                    msg: message
                    ts: timestamp
          - timestamp:
                source: ts
                format: RFC3339Nano
